// Generated by scripts/generate-page-dates.mjs. Do not edit by hand.
// Date of the last change to each page's source file, used for sitemap <lastmod>.
export const PAGE_DATES: Record<string, string> = {
  "/": "2026-09-15",
  "/about-us": "2026-09-15",
  "/team": "2026-09-15",
  "/contact": "2026-09-15",
  "/faq": "2026-09-15",
  "/handbook": "2026-09-15",
  "/blog": "2026-09-15",
  "/phone-mast-rent-2026": "2026-09-15",
  "/phone-mast-lease-2026": "2026-09-15",
  "/phone-mast-solicitors": "2026-09-15",
  "/electronic-communications-code": "2026-09-15",
  "/section-26-notice": "2026-09-15",
  "/phone-mast-services": "2026-09-15",
  "/phone-mast-services/rent-reviews": "2026-09-15",
  "/phone-mast-services/lease-renewals": "2026-09-15",
  "/phone-mast-services/new-lettings": "2026-09-15",
  "/phone-mast-services/mast-sales": "2026-09-15",
  "/phone-mast-services/removal-and-redevelopment": "2026-09-15",
  "/phone-mast-services/electricity-costs-recovery": "2026-09-15",
  "/phone-mast-services/other-services": "2026-09-15",
  "/phone-mast-services/lease-retrievals": "2026-09-15",
  "operator": "2026-09-15",
  "location": "2026-09-15"
};
